TEST_ENTRIES = [{'title': 'On-duty police officer sexually assaulted by gas station manager, Georgia cops say',
                 'title_detail': {'type': 'text/plain', 'language': None, 'base': 'https://news.yahoo.com/rss/',
                                  'value': 'On-duty police officer sexually assaulted by gas station manager, Georgia cops say'},
                 'links': [{'rel': 'alternate', 'type': 'text/html',
                            'href': 'https://news.yahoo.com/duty-police-officer-sexually-assaulted-010634049.html'}],
                 'link': 'https://news.yahoo.com/duty-police-officer-sexually-assaulted-010634049.html',
                 'published': '2021-05-18T01:06:34Z',
                 'source': {'href': 'https://www.kentucky.com/', 'title': 'Lexington Herald-Leader'},
                 'id': 'duty-police-officer-sexually-assaulted-010634049.html', 'guidislink': False, 'media_content': [
        {'height': '86',
         'url': 'https://s.yimg.com/uu/api/res/1.2/A3riyROEGQuSpO0M838c0g--~B/aD02NDE7dz0xMTQwO2FwcGlkPXl0YWNoeW9u/https://media.zenfs.com/en/lexington_herald_leader_mcclatchy_articles_314/d453d37647ec075638a8bc71a3e80ce0',
         'width': '130'}], 'media_credit': [{'role': 'publishing company'}], 'credit': ''},
                {'title': 'Heroic Dog Who Lost Her Snout Saving Two Girls Years Ago Passes Away in the Philippines',
                 'title_detail': {'type': 'text/plain', 'language': None, 'base': 'https://news.yahoo.com/rss/',
                                  'value': 'Heroic Dog Who Lost Her Snout Saving Two Girls Years Ago Passes Away in the Philippines'},
                 'links': [{'rel': 'alternate', 'type': 'text/html',
                            'href': 'https://news.yahoo.com/heroic-dog-lost-her-snout-151239087.html'}],
                 'link': 'https://news.yahoo.com/heroic-dog-lost-her-snout-151239087.html',
                 'published': '2021-05-18T15:12:39Z',
                 'source': {'href': 'https://nextshark.com/', 'title': 'NextShark'},
                 'id': 'heroic-dog-lost-her-snout-151239087.html', 'guidislink': False, 'media_content': [
                    {'height': '86',
                     'url': 'https://s.yimg.com/uu/api/res/1.2/rSALC6BHE5GLgr.puYJEuA--~B/aD00MjU7dz04MDA7YXBwaWQ9eXRhY2h5b24-/https://media.zenfs.com/en/nextshark_articles_509/1939d15898adc9f02b3aa5266f51881a',
                     'width': '130'}], 'media_credit': [{'role': 'publishing company'}], 'credit': ''},
                {'title': '600,000 kids between 12 and 15 have received Pfizer vaccine dose since FDA authorization',
                 'title_detail': {'type': 'text/plain', 'language': None, 'base': 'https://news.yahoo.com/rss/',
                                  'value': '600,000 kids between 12 and 15 have received Pfizer vaccine dose since FDA authorization'},
                 'links': [{'rel': 'alternate', 'type': 'text/html',
                            'href': 'https://news.yahoo.com/600-000-kids-between-12-151913054.html'}],
                 'link': 'https://news.yahoo.com/600-000-kids-between-12-151913054.html',
                 'published': '2021-05-18T15:19:13Z', 'source': {'href': 'https://www.axios.com/', 'title': 'Axios'},
                 'id': '600-000-kids-between-12-151913054.html', 'guidislink': False, 'media_content': [{'height': '86',
                                                                                                         'url': 'https://s.yimg.com/uu/api/res/1.2/u194wekMUQEk_9oy8lv3Iw--~B/aD03MjA7dz0xMjgwO2FwcGlkPXl0YWNoeW9u/https://media.zenfs.com/en/axios_articles_623/0ed6f0918ef60763f094e36c4bcc43f4',
                                                                                                         'width': '130'}],
                 'media_credit': [{'role': 'publishing company'}], 'credit': ''}]
